import 'xyz'
import 'assert'
import 'node:domain'
import A from 'node:module'
import {B} from 'my_module'
import * as C from '@abc'
import D, {E} from './aaa'
import {F,G} from 'node:dns'
import H from 'node:bbb'